# Generated by Django 6.0.6 on 2026-06-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='RG',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dataNascimento',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nomeMae',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nomePai',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(default='', max_length=1),
        ),
    ]
