# Generated by Django 6.0.6 on 2026-06-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleubs', '0002_paciente_rg_paciente_datanascimento_paciente_nomemae_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='horarioExame',
            field=models.TimeField(default=None, null=True),
        ),
    ]
